#pragma once
// Auto-generated by NDS Studio Exporter
// Source: iwatodai_dorm_floor_1
// Scale: 0.001221
// DO NOT EDIT - regenerate from source.

#include <math.h>
#include <nds.h>
#include <stdio.h>
#include <stdlib.h>

#define IWATODAI_DORM_FLOOR_1_WORLD_OFFSET_X 0.000000f
#define IWATODAI_DORM_FLOOR_1_WORLD_OFFSET_Z -2.000000f
#define IWATODAI_DORM_FLOOR_1_WORLD_WIDTH 2.523659f
#define IWATODAI_DORM_FLOOR_1_WORLD_DEPTH 4.000000f

static const char* const iwatodai_dorm_floor_1_TextureFilenames[33] = {
    "f007_002wall01", "f007_002wall02",    "f007_002wall03",  "f007_002door02",  "f007_002kzr01",   "f007_002kzr02",
    "f007_002obj01",  "f007_002obj04",     "f007_002obj07",   "f007_002obj11",   "f007_002wall04",  "f007_002wall05",
    "f007_002wall06", "f007_002step01",    "f007_002step02",  "f007_002kzr03",   "f007_002kzr04",   "f007_002obj09",
    "f007_002bolt01", "f007_002obj03",     "f007_002floor01", "f007_002floor02", "f007_002floor03", "f007_002obj02",
    "f007_002obj05",  "f007_002obj15",     "f007_002bolt03",  "f007_002obj13",   "f007_002obj12",   "f007_002door01",
    "f007_002obj10",  "f007_002obj03_png", "akihiko_png",
};

enum iwatodai_dorm_floor_1_TexSlot
{
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL01 = 0,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL02 = 1,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL03 = 2,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002DOOR02 = 3,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002KZR01 = 4,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002KZR02 = 5,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ01 = 6,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ04 = 7,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ07 = 8,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ11 = 9,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL04 = 10,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL05 = 11,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002WALL06 = 12,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002STEP01 = 13,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002STEP02 = 14,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002KZR03 = 15,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002KZR04 = 16,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ09 = 17,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002BOLT01 = 18,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ03 = 19,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002FLOOR01 = 20,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002FLOOR02 = 21,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002FLOOR03 = 22,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ02 = 23,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ05 = 24,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ15 = 25,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002BOLT03 = 26,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ13 = 27,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ12 = 28,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002DOOR01 = 29,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ10 = 30,
    IWATODAI_DORM_FLOOR_1_TEX_F007_002OBJ03_PNG = 31,
    IWATODAI_DORM_FLOOR_1_TEX_AKIHIKO_PNG = 32,
    IWATODAI_DORM_FLOOR_1_TEX_COUNT = 33
};

struct iwatodai_dorm_floor_1_BillboardData
{
    v16 x, y, z;
    v16 halfWidth, halfHeight;
    int texSlot;
    short u0, v0, u1, v1;
};

class iwatodai_dorm_floor_1_Environment
{
  public:
    u32* displayLists[33];
    u32 dlSizes[33];
    int textureIDs[33];

    static const int BILLBOARD_COUNT = 0;
    const iwatodai_dorm_floor_1_BillboardData BILLBOARDS[1] = {0};

    iwatodai_dorm_floor_1_Environment()
    {
        for (int i = 0; i < 33; i++)
        {
            displayLists[i] = NULL;
            dlSizes[i] = 0;
            textureIDs[i] = 0;
        }
    }

    bool load(const char* filepath, const unsigned int* bitmaps[33])
    {
        FILE* file = fopen(filepath, "rb");
        if (!file)
            return false;

        char magic[4];
        fread(magic, 1, 4, file);
        if (magic[0] != 'E' || magic[1] != 'N' || magic[2] != 'V' || magic[3] != '1')
        {
            fclose(file);
            return false;
        }

        u32 groupCount;
        fread(&groupCount, sizeof(u32), 1, file);
        if (groupCount != 33)
        {
            fclose(file);
            return false;
        }

        for (u32 i = 0; i < groupCount; i++)
        {
            fread(&dlSizes[i], sizeof(u32), 1, file);
            displayLists[i] = (u32*)malloc((dlSizes[i] + 1) * sizeof(u32));
            displayLists[i][0] = dlSizes[i];
            if (dlSizes[i] > 0)
                fread(&displayLists[i][1], sizeof(u32), dlSizes[i], file);
        }
        fclose(file);

        if (bitmaps[0])
        {
            glGenTextures(1, &textureIDs[0]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[0]);
        }
        if (bitmaps[1])
        {
            glGenTextures(1, &textureIDs[1]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[1]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[1]);
        }
        if (bitmaps[2])
        {
            glGenTextures(1, &textureIDs[2]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[2]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_32,
                         TEXTURE_SIZE_32,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[2]);
        }
        if (bitmaps[3])
        {
            glGenTextures(1, &textureIDs[3]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[3]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[3]);
        }
        if (bitmaps[4])
        {
            glGenTextures(1, &textureIDs[4]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[4]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[4]);
        }
        if (bitmaps[5])
        {
            glGenTextures(1, &textureIDs[5]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[5]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[5]);
        }
        if (bitmaps[6])
        {
            glGenTextures(1, &textureIDs[6]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[6]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[6]);
        }
        if (bitmaps[7])
        {
            glGenTextures(1, &textureIDs[7]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[7]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[7]);
        }
        if (bitmaps[8])
        {
            glGenTextures(1, &textureIDs[8]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[8]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[8]);
        }
        if (bitmaps[9])
        {
            glGenTextures(1, &textureIDs[9]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[9]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[9]);
        }
        if (bitmaps[10])
        {
            glGenTextures(1, &textureIDs[10]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[10]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_32,
                         TEXTURE_SIZE_32,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[10]);
        }
        if (bitmaps[11])
        {
            glGenTextures(1, &textureIDs[11]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[11]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[11]);
        }
        if (bitmaps[12])
        {
            glGenTextures(1, &textureIDs[12]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[12]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_32,
                         TEXTURE_SIZE_32,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[12]);
        }
        if (bitmaps[13])
        {
            glGenTextures(1, &textureIDs[13]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[13]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[13]);
        }
        if (bitmaps[14])
        {
            glGenTextures(1, &textureIDs[14]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[14]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_32,
                         TEXTURE_SIZE_32,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[14]);
        }
        if (bitmaps[15])
        {
            glGenTextures(1, &textureIDs[15]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[15]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[15]);
        }
        if (bitmaps[16])
        {
            glGenTextures(1, &textureIDs[16]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[16]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[16]);
        }
        if (bitmaps[17])
        {
            glGenTextures(1, &textureIDs[17]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[17]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[17]);
        }
        if (bitmaps[18])
        {
            glGenTextures(1, &textureIDs[18]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[18]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[18]);
        }
        if (bitmaps[19])
        {
            glGenTextures(1, &textureIDs[19]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[19]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[19]);
        }
        if (bitmaps[20])
        {
            glGenTextures(1, &textureIDs[20]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[20]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[20]);
        }
        if (bitmaps[21])
        {
            glGenTextures(1, &textureIDs[21]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[21]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[21]);
        }
        if (bitmaps[22])
        {
            glGenTextures(1, &textureIDs[22]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[22]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[22]);
        }
        if (bitmaps[23])
        {
            glGenTextures(1, &textureIDs[23]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[23]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[23]);
        }
        if (bitmaps[24])
        {
            glGenTextures(1, &textureIDs[24]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[24]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[24]);
        }
        if (bitmaps[25])
        {
            glGenTextures(1, &textureIDs[25]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[25]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[25]);
        }
        if (bitmaps[26])
        {
            glGenTextures(1, &textureIDs[26]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[26]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_32,
                         TEXTURE_SIZE_32,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[26]);
        }
        if (bitmaps[27])
        {
            glGenTextures(1, &textureIDs[27]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[27]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[27]);
        }
        if (bitmaps[28])
        {
            glGenTextures(1, &textureIDs[28]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[28]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_32,
                         TEXTURE_SIZE_32,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[28]);
        }
        if (bitmaps[29])
        {
            glGenTextures(1, &textureIDs[29]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[29]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[29]);
        }
        if (bitmaps[30])
        {
            glGenTextures(1, &textureIDs[30]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[30]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[30]);
        }
        if (bitmaps[31])
        {
            glGenTextures(1, &textureIDs[31]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[31]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_64,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[31]);
        }
        if (bitmaps[32])
        {
            glGenTextures(1, &textureIDs[32]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[32]);
            glTexImage2D(GL_TEXTURE_2D,
                         0,
                         GL_RGBA,
                         TEXTURE_SIZE_32,
                         TEXTURE_SIZE_64,
                         0,
                         TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                         bitmaps[32]);
        }
        return true;
    }

    void draw()
    {
        glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
        if (displayLists[0])
            glCallList(displayLists[0]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[1]);
        if (displayLists[1])
            glCallList(displayLists[1]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[2]);
        if (displayLists[2])
            glCallList(displayLists[2]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[3]);
        if (displayLists[3])
            glCallList(displayLists[3]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[4]);
        if (displayLists[4])
            glCallList(displayLists[4]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[5]);
        if (displayLists[5])
            glCallList(displayLists[5]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[6]);
        if (displayLists[6])
            glCallList(displayLists[6]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[7]);
        if (displayLists[7])
            glCallList(displayLists[7]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[8]);
        if (displayLists[8])
            glCallList(displayLists[8]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[9]);
        if (displayLists[9])
            glCallList(displayLists[9]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[10]);
        if (displayLists[10])
            glCallList(displayLists[10]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[11]);
        if (displayLists[11])
            glCallList(displayLists[11]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[12]);
        if (displayLists[12])
            glCallList(displayLists[12]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[13]);
        if (displayLists[13])
            glCallList(displayLists[13]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[14]);
        if (displayLists[14])
            glCallList(displayLists[14]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[15]);
        if (displayLists[15])
            glCallList(displayLists[15]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[16]);
        if (displayLists[16])
            glCallList(displayLists[16]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[17]);
        if (displayLists[17])
            glCallList(displayLists[17]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[18]);
        if (displayLists[18])
            glCallList(displayLists[18]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[19]);
        if (displayLists[19])
            glCallList(displayLists[19]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[20]);
        if (displayLists[20])
            glCallList(displayLists[20]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[21]);
        if (displayLists[21])
            glCallList(displayLists[21]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[22]);
        if (displayLists[22])
            glCallList(displayLists[22]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[23]);
        if (displayLists[23])
            glCallList(displayLists[23]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[24]);
        if (displayLists[24])
            glCallList(displayLists[24]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[25]);
        if (displayLists[25])
            glCallList(displayLists[25]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[26]);
        if (displayLists[26])
            glCallList(displayLists[26]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[27]);
        if (displayLists[27])
            glCallList(displayLists[27]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[28]);
        if (displayLists[28])
            glCallList(displayLists[28]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[29]);
        if (displayLists[29])
            glCallList(displayLists[29]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[30]);
        if (displayLists[30])
            glCallList(displayLists[30]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[31]);
        if (displayLists[31])
            glCallList(displayLists[31]);
        while (GFX_BUSY)
            ;
        glBindTexture(GL_TEXTURE_2D, textureIDs[32]);
        if (displayLists[32])
            glCallList(displayLists[32]);
        while (GFX_BUSY)
            ;
    }

    void cleanup()
    {
        for (u32 i = 0; i < 33; i++)
        {
            if (displayLists[i])
            {
                free(displayLists[i]);
                displayLists[i] = NULL;
            }
        }
        glDeleteTextures(33, textureIDs);
    }
};
